site_name: OpenCV Python Tutorials
theme: readthedocs
nav:
- 主页: 'index.md'
- 1. OpenCV简介:
  - 1.1. OpenCV-Python教程介绍: '1. OpenCV简介/1.1. OpenCV-Python教程介绍.md'
- 2. OpenCV中的 Gui特性:
  - 2.1. 图像入门: '2. OpenCV中的 Gui特性/2.1. 图像入门.md'
  - 2.2. 视频入门: '2. OpenCV中的 Gui特性/2.2. 视频入门.md'
  - 2.3. OpenCV中的绘图功能: '2. OpenCV中的 Gui特性/2.3. OpenCV中的绘图功能.md'
  - 2.4. 把鼠标作为画笔: '2. OpenCV中的 Gui特性/2.4. 把鼠标作为画笔.md'
  - 2.5. 用滑动条做调色板: '2. OpenCV中的 Gui特性/2.5. 用滑动条做调色板.md'
- 3. 核心操作:
  - 3.1. 图像的基本操作: '3. 核心操作/3.1. 图像的基本操作.md'
  - 3.2. 图像的算术运算: '3. 核心操作/3.2. 图像的算术运算.md'
  - 3.3. 绩效评估和改进技术: '3. 核心操作/3.3. 绩效评估和改进技术.md'
- 4. OpenCV中的图像处理:
  - 4.1. 改变颜色空间: '4. OpenCV中的图像处理/4.1. 改变颜色空间.md'
  - 4.2. 图像的几何变换: '4. OpenCV中的图像处理/4.2. 图像的几何变换.md'
  - 4.3. 图像阈值: '4. OpenCV中的图像处理/4.3. 图像阈值.md'
  - 4.4. 图像滤波: '4. OpenCV中的图像处理/4.4. 图像滤波.md'
  - 4.5. 形态变换: '4. OpenCV中的图像处理/4.5. 形态变换.md'
  - 4.6. 图形梯度: '4. OpenCV中的图像处理/4.6. 图形梯度.md'
  - 4.7. Canny边缘检测: '4. OpenCV中的图像处理/4.7. Canny边缘检测.md'
  - 4.8. 图像金字塔: '4. OpenCV中的图像处理/4.8. 图像金字塔.md'
  - 4.9.1. 轮廓：入门: '4. OpenCV中的图像处理/4.9.1. 轮廓：入门.md'
  - 4.9.2. 轮廓特征: '4. OpenCV中的图像处理/4.9.2. 轮廓特征.md'
  - 4.9.3. 轮廓属性: '4. OpenCV中的图像处理/4.9.3. 轮廓属性.md'
  - 4.9.4. 轮廓：更多函数: '4. OpenCV中的图像处理/4.9.4. 轮廓：更多函数.md'
  - 4.9.5. 轮廓：层次结构: '4. OpenCV中的图像处理/4.9.5. 轮廓：层次结构.md'
  - 4.10.1 直方图1：查找，绘画，分析: '4. OpenCV中的图像处理/4.10.1 直方图1：查找，绘画，分析.md'
  - 4.10.2 直方图2：均衡直方图: '4. OpenCV中的图像处理/4.10.2 直方图2：均衡直方图.md'
  - 4.10.3. 直方图3：2D直方图: '4. OpenCV中的图像处理/4.10.3. 直方图3：2D直方图.md'
  - 4.10.4. 反投影直方图: '4. OpenCV中的图像处理/4.10.4. 反投影直方图.md'
  - 4.11.1 傅里叶变换: '4. OpenCV中的图像处理/4.11.1 傅里叶变换.md'
  - 4.12. 模板匹配: '4. OpenCV中的图像处理/4.12. 模板匹配.md'
  - 4.13. 霍夫线变换: '4. OpenCV中的图像处理/4.13. 霍夫线变换.md'
  - 4.14. 霍夫圆变换: '4. OpenCV中的图像处理/4.14. 霍夫圆变换.md'
  - 4.15. 基于分水岭算法的图像分割: '4. OpenCV中的图像处理/4.15. 基于分水岭算法的图像分割.md'
  - 4.16. 基于GrabCut算法的交互式前景提取: '4. OpenCV中的图像处理/4.16. 基于GrabCut算法的交互式前景提取.md'
- 5. 特征检测和描述:
  - 5.1. 了解特征: '5. 特征检测和描述/5.1. 了解特征.md'
  - 5.2. Harris角点检测: '5. 特征检测和描述/5.2. Harris角点检测.md'
  - 5.3. Shi-Tomasi角点检测和特征追踪: '5. 特征检测和描述/5.3. Shi-Tomasi角点检测和特征追踪.md'
  - 5.4. SIFT(Scale-Invariant Feature Transform)简介: '5. 特征检测和描述/5.4. SIFT(Scale-Invariant Feature Transform)简介.md'
  - 5.5. SURF (Speeded-Up Robust Features)简介: '5. 特征检测和描述/5.5. SURF (Speeded-Up Robust Features)简介.md'
  - 5.6. 用于角点检测的FAST算法: '5. 特征检测和描述/5.6. 用于角点检测的FAST算法.md'
  - 5.7. BRIEF (Binary Robust Independent Elementary Features): '5. 特征检测和描述/5.7. BRIEF (Binary Robust Independent Elementary Features).md'
  - 5.8. ORB (Oriented FAST and Rotated BRIEF): '5. 特征检测和描述/5.8. ORB (Oriented FAST and Rotated BRIEF).md'
  - 5.9. 特征匹配: '5. 特征检测和描述/5.9. 特征匹配.md'
  - 5.10. 特征匹配结合单应性去查找对象: '5. 特征检测和描述/5.10. 特征匹配结合单应性去查找对象.md'
- 6. 视频分析:
  - 6.1. Meanshift和Camshift: '6. 视频分析/6.1. Meanshift和Camshift.md'
  - 6.2. 光流: '6. 视频分析/6.2. 光流.md'
  - 6.3. 背景差分法: '6. 视频分析/6.3. 背景差分法.md'
- 7. 相机校准和3D重建:
  - 7.1. 相机校准: '7. 相机校准和3D重建/7.1. 相机校准.md'
  - 7.2. 姿势估计: '7. 相机校准和3D重建/7.2. 姿势估计.md'
  - 7.3. 对极几何: '7. 相机校准和3D重建/7.3. 对极几何.md'
  - 7.4. 立体图像的深度图: '7. 相机校准和3D重建/7.4. 立体图像的深度图.md'
- 8. 机器学习:
  - 8.1. K近邻: '8. 机器学习/8.1. K近邻.md'
  - 8.2.1 理解支持向量机: '8. 机器学习/8.2.1. 理解支持向量机.md'
  - 8.2.2. 在手写数据集上使用支持向量机进行OCR: '8. 机器学习/8.2.2. 在手写数据集上使用支持向量机进行OCR.md'
  - 8.3. K均值聚类: '8. 机器学习/8.3. K均值聚类.md'
- 9. 计算摄影:
  - 9.1. 图像去噪: '9. 计算摄影/9.1. 图像去噪.md'
  - 9.2. 图像修复: '9. 计算摄影/9.2. 图像修复.md'
  - 9.3. 高动态范围（HDR）: '9. 计算摄影/9.3. 高动态范围（HDR）.md'
- 10. 目标检测:
  - 10.1. 采用Haar Cascades进行人脸检测: '10. 目标检测/10.1. 采用Haar Cascades进行人脸检测.md'
